#!/bin/bash
while [[ $# > 1 ]]
do
key="$1"

case $key in
    -d|--db-name)
    DB_NAME="$2"
    shift
    ;;
    -p|--path)
    INSTALLPATH="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
shift
done

PASSWORD=`openssl rand -hex 8`

if [ "$INSTALLPATH" == "" ]; then
    printf "\033[34mEnter a path for this installation.  The directory will be created or overwritten.  [Defaults to ./wordpress]\n> \033[0m"
    read INSTALLPATH
fi

if [ "$DB_NAME" == "" ]; then
    printf "\033[34mWhat database name would you like to use? [16 char max, a-z A-Z 0-9 $ _ only]\n> \033[0m"
    read DB_NAME
fi

if [ -d "${INSTALLPATH}" ]; then
    printf "\033[31mThe install path specified already exists!  Delete it, then try again.\n\033[0m"
    exit
fi


if [ -d "wordpress" ]; then
    printf "\033[31mWARNING: The wordpress/ directory already exists here!  Type YES to overwrite or anything else to quit.\n\033[0m"
    read CONFIRM_WP_DIR
    if [ "$CONFIRM_WP_DIR" != "YES" ]; then
        printf "\033[31mExiting without action.\n\033[0m"
        exit
    fi
fi

#####################
# file operations
#####################

printf "\033[36m* \033[32m\e[0;32mDownloading the latest version of WordPress\n\033[0m"
wget --no-verbose http://wordpress.org/latest.tar.gz

printf "\033[36m* \033[32mUnpacking archive\n\033[0m"
tar -xzf latest.tar.gz

if [ "$INSTALLPATH" == "" ]; then
    let INSTALLPATH="./wordpress"
fi

printf "\033[36m* \033[32mMoving install to specified path\n\033[0m"
mv wordpress/ ${INSTALLPATH}

printf "\033[36m* \033[32mDeleting archive\n\033[0m"
rm latest.tar.gz

printf "\033[36m* \033[32mSetting up database in MySQL\n\033[0m"
mysql -u root -p -e "CREATE DATABASE ${DB_NAME};CREATE USER '${DB_NAME}'@'localhost' IDENTIFIED BY '${PASSWORD}';GRANT ALL ON ${DB_NAME}.* TO '${DB_NAME}'@'localhost' IDENTIFIED BY '${PASSWORD}';"

#####################
# wp-config.php setup
#####################

# have to handle sed syntax differently on OSX and Ubuntu.  
run_sed_cmd()
{
    SED_CMD=$1
    FIND=$2
    REPLACE=$3
    ${SED_CMD} -e"1,/${FIND}/ s/${FIND}/${REPLACE}/" ${INSTALLPATH}/wp-config.php
}


OS=`uname -s`
if [ "${OS}" == "Darwin" ]; then
    find_and_replace() {
        FIND=$1
        REPLACE=$2
        run_sed_cmd "sed -i ''" "${FIND}" "${REPLACE}"
    }
else
    find_and_replace() {
        FIND=$1
        REPLACE=$2
        run_sed_cmd "sed -i''" "${FIND}" "${REPLACE}"
    }
fi

printf "\033[36m* \033[32mSetting database config in wp-config.php\n\033[0m"
cp ${INSTALLPATH}/wp-config-sample.php ${INSTALLPATH}/wp-config.php
find_and_replace 'database_name_here' ${DB_NAME}
find_and_replace 'username_here' ${DB_NAME}
find_and_replace 'password_here' ${PASSWORD}

printf "\033[36m* \033[32mSetting security salts in wp-config.php\n\033[0m"
for i in `seq 1 8`;
do
    find_and_replace 'put your unique phrase here' `openssl rand -hex 32`
done

printf "\033[32m----------------------------------------\n\033[0m"
echo '              BOOM, DONE'
printf "\033[32m----------------------------------------\n\033[0m"