#!/bin/bash
THISDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$THISDIR"/db-operations
REPODIR=$(git rev-parse --show-toplevel)
mkdir -p "$REPODIR"/db
mysqldump -u $DBUSER --password=$DBPASS $DBNAME > "$WPDIR""$DBDIRECTORY""$DBNAME".sql
git add "$REPODIR"/db
